### ISSUE TITLE
dSYM Path With Spaces

### ISSUE THREAD

**Issue by chrisdhaan** [sophos7/multidsym_upload#2]
When Xcode archives my application the archive contains spaces in the name. It looks like the script provided fails on the ```find``` command due to the spaces in the path. Do you happen to know how to fix this besides having to change the name of the archive folder?

**Comment by sophos7** [comment]
Hm, I'm surprised that spaces in the dSYM name caused the failure. I specifically tested for this condition when originally creating the script. This is why I used `find` in the first place.

I actually recently updated the script because of an issue with dSYMs that have build uuid for multiple architectures. I wonder if that's where this is failing. I'll look into the issue.

**Comment by sophos7** [comment]
@chrisdhaan looks like I failed to bring over some quote marks from my initial testing, doh! Sorry about that. I updated and ran new tests with spaces in the folder path. Seems to be working fine now.

**Comment by chrisdhaan** [comment]
@sophos7 awesome! Thanks so much
